name: nuts
description: >
  Nuts and bolts for building cross-platform UI (HTML, Flutter, CLI) using Dart. Also screw frameworks (React, Vue,
  Angular).
version: 1.0.1
homepage: https://github.com/Jaguar-dart/nuts
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  collection:

# dev_dependencies:
#  build_runner: ^0.8.7
#  build_web_compilers: ^0.4.0
