name: nuts
description: >
  Nuts and bolts for building cross-platform UI (HTML, Flutter, CLI) using Dart. Also screw frameworks (React, Vue,
  Angular).
version: 2.1.4
homepage: https://github.com/Jaguar-dart/nuts
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.65.0 <3.0.0'

dependencies:
  collection: ^1.14.10
  observable_ish: ^2.1.4

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
